# master的名字是sentinel.conf配置文件里面的名称
# sentinel monitor redis-master 192.168.8.203 6379 2
spring:
  redis:
    sentinel:
      master: redis-master
      nodes:  192.168.8.203:26379,192.168.8.204:26379,192.168.8.205:26379
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1s # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0


  datasource:
    url: jdbc:mysql://localhost:3306/iris?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
      cache: false

mybatis:
  typeAliasesPackage: com.iris.entity
  mapperLocations:  classpath:mapper/*.xml

