server:
  port: 8000
rocketmq:
  producer:
    isOnOff: on #该应用是否启用生产者
    groupName: group1
    namesrvAddr: 127.0.0.1:9876
    maxMessageSize: 4096
    sendMsgTimeout: 30000
    retryTimesWhenSendFailed: 2
  consumer:
    isOnOff: on #该应用是否启用消费者
    groupName: group1
    namesrvAddr: 127.0.0.1:9876
    topics: lwr_topic~*;
    consumeThreadMin: 20
    consumeThreadMax: 64
    consumeMessageBatchMaxSize: 1
spring:
  main:
    allow-bean-definition-overriding: true