#开发环境配置
spring:
  devtools:
    restart:
      enabled : true # 指定热部署的目录
      exclude : test # 指定目录不更新
server:
  port: 8081


#  redis: #单机windows redis 运行> redis-server.exe redis.windows.conf
#    #>redis-cli.exe -h 127.0.0.1 -p 6379
#    database : 0 # Redis数据库索引（默认为0）
#    host : 127.0.0.1 # Redis服务器地址
#    port : 6379
#    password: lwr123123
#  #redis.timeout=3 ## 连接超时时间（毫秒）
#  #spring.devtools.restart.additional-paths: src/main/java
#
#  #对于rabbitMQ的支持
#  rabbitmq :
#    host : 127.0.0.1
#    port : 5672
#    username : guest
#    password : guest

my :
  name : lwr-dev
  age : 26
  uuid : dev-${random.uuid}
  number : ${random.int(20)}