server:
  port: 9096

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowable?useUnicode=true&characterEncoding=utf8
    username: root
    password: 13755886712Lwrong
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: flowable
flowable:
  check-process-definitions: true